# Blog info
blog_name: Netcan on Programming
slogan: Coding Life
url: https://netcan.github.io

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: C/C++,Rust,软件工程,重构,软件架构,DDD

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
  - name: Talks
    url: /talks
    target_blank: false #不在新页面打开
  - name: About
    url: /about
    target_blank: false #不在新页面打开
  - name: Project
    url: /project/
    target_blank: true #在新页面打开
  # - name: Github
    # url: https://github.com/netcan
    # target_blank: true
  # - name: Zhihu
    # url: https://www.zhihu.com/people/netcan
    # target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  # - name: 友链
    # url: /link/
    # target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: ROOT

search_slogan:
  isShow: true # true|fase
  text: Search...

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件 netcan1996@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持Netcan
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/site.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

blog_name_font_familiy: calligraffittiregular
init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics: UA-174901164-1
baidu_analytics: d2c292719a76d8c0fa7f9874379cfd25

# Comment service

# disqus_shortname: netcan
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

#有言用户编号
# uyan_key:

# 畅言, doc: http://changyan.kuaizhan.com/
changyan:
  enable: false  # true | false  这里开启
  changyan_appid:
  changyan_appkey:

# gitalk评论组件，把下面的配置换成你的，官方文档: https://gitalk.github.io/
gitalk:
  enable: true # 如果使用 gitalk，请设置改之为true
  clientID: 893a4103795fc66cd8e7
  clientSecret: 35c92c3dca938831b67dc22e46d64bc9073ebacf
  repo: netcan.github.io
  owner: Netcan
  admin: Netcan


# gitment comment service
gitment:
  enable: false  # true | false  这里开启
  owner:  # Your GitHub ID. Required.
  repo:  # The repository to store your comments. Make sure you're repo's owner. Required.
  oauth: # An object contains your client ID and client secret. Required.
    client_id: # GitHub client ID. Required.
    client_secret: # GitHub client secret. Required.
  id: # An optional string to identify your page. Default location.href.
  title: # An optional title for your page, used as issue's title. Default document.title.
  link: # An optional link for your page, used in issue's body. Default location.href.
  desc: # An optional description for your page, used in issue's body. Default ''.
  labels: # An optional array of labels your want to add when creating the issue. Default [].
  theme: # An optional Gitment theme object. Default gitment.defaultTheme.
  perPage: # An optional number to which comments will be paginated. Default 20.
  maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Netcan, 1996, Summer."
    - "Software Engineer，Love C/C++/Rust/Lisp/Haskell"
    - "Interests: OO, FP, Design, Coding"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@netcan"
    text_value_url: https://github.com/netcan
  - type: Zhihu
    icon: icon-user
    text_key: Zhihu
    text_value: "@netcan"
    text_value_url: https://www.zhihu.com/people/netcan
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "netcan1996@gmail.com"
  - type: location
    icon: icon-location
    text_value:
    - 上海华为研究所. 2018.7 ~ Today
    - 合肥工业大学. 2014.7 ~ 2018.6

link:
  # - name:
    # info:
    # url:
    # avatar:

project:
  - type: personal
    name: netcan.github.io
    url: https://github.com/netcan/netcan.github.io
    intro: My blog for something about programming.
  - type: personal
    name: AnimalChess
    url: https://github.com/netcan/AnimalChess
    intro: Animal Fight Chess Game（斗兽棋） written in rust.
  - type: personal
    name: NetcanOS
    url: https://github.com/netcan/NetcanOS
    intro: Netcan OS is an operation system for x86 PCs, for learning how os works.
  - type: personal
    name: HFUT_Thesis
    url: https://github.com/netcan/HFUT_Thesis
    intro: 合肥工业大学毕业设计（论文）模板
  - type: personal
    name: libnetcan-soft.so
    url: https://github.com/netcan/libnetcan-soft.so
    intro: A utility library written in junior high school. on birthday 2012-05-23.
  - type: personal
    name: FCEmulator
    url: https://github.com/netcan/FCEmulator
    intro: 毕业设计项目，FC模拟器。
  - type: personal
    name: LinAlg
    url: https://github.com/netcan/LinAlg
    intro: 实现一个线性代数库，为Python写扩展。《程序猿的数学3 线性代数》读后笔记。
  - type: personal
    name: compilingTheory
    url: https://github.com/netcan/compilingTheory
    intro: My course design for compiler theory (Visualization).
  - type: personal
    name: LoveCalendar
    url: https://github.com/netcan/LoveCalendar
    intro: A calendar to mark something.
  - type: personal
    name: HFUT_Market
    url: https://github.com/netcan/HFUT_Market
    intro: A databases course design, using python.
  - type: personal
    name: Talk
    url: https://github.com/netcan/Talk
    intro: A simple Java talk software.
  - type: personal
    name: HFUT_Live
    url: https://github.com/netcan/HFUT_Live
    intro: 校内直播平台。
  - type: personal
    name: baike_contest
    url: https://github.com/netcan/baike_contest
    intro: 合工大宣百科竞赛平台
  - type: personal
    name: SlidePuzzle
    url: https://github.com/netcan/SlidePuzzle
    intro: Slide puzzle game written by Netcan. using the SDL engine and use of A* algorithm.
  - type: personal
    name: 2017-HUAWEI-Codecraft
    url: https://github.com/netcan/2017-HUAWEI-Codecraft
    intro: 2017华为软件精英挑战赛，上合赛区，围墙编队
  - type: personal
    name: 2018-HUAWEI-Codecraft
    url: https://github.com/netcan/2018-HUAWEI-Codecraft
    intro: 2017华为软件精英挑战赛，上合赛区，围墙编队
  - type: personal
    name: Laravel_AJAX_CRUD
    url: https://github.com/netcan/Laravel_AJAX_CRUD
    intro: A Laravel application for AJAX CRUD page.
  - type: personal
    name: HFUT_ChemLab
    url: https://github.com/netcan/HFUT_ChemLab
    intro: A Laravel application for HFUT Chemistry lab learning and exam system.
  - type: personal
    name: gameOfLife
    url: https://github.com/netcan/gameOfLife
    intro: game of life using Javascript and canvas.
